basic structure
shahira-sadat/Leaderboard pull request #2
Opened 2022-07-18 21:57 UTC by shahira-sadat

Hi, Thanks for your review.

Following is the list of activities done for this PR 👇🏻:

1. Create an npm project with webpack.
2. Use Gitflow
3. Write plain HTML markup with minimum styling
4. Create modules for generating score `data.js`  and adding score `score.js`
5. Use ES6 modules, with import and export.

2022-07-18 22:51 UTC, CollinsTatang requested changes
Hi @shahira-sadat, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-18 22:51 UTC, CollinsTatang commented on package.json
> +    "hint": "^2.0.0",
Hello @shahira-sadat 
Great job so far implementing the project requirements.

- [ ] Your app throws an error when I try to start it with webpack `npm run start`. Indicating that you are missing some `package.json` dependencies.
![solutio](https://user-images.githubusercontent.com/55596970/179629813-1e159ee3-63d7-492c-9e16-5c4698132ffd.png)
### **SOLUTION**
You can install the missing dependencies by running this command on your terminal from your project root directory.
`npm install --save-dev babel-loader @babel/core @babel/preset-env webpack`

2022-07-19 00:19 UTC, shahira-sadat commented on package.json
> +    "hint": "^2.0.0",
Done

2022-07-19 00:30 UTC, prolajumokeoni approved these changes
Hi @shahira-sadat, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 02:16 UTC, merged